"""empty message

Revision ID: 95d9b914caac
Revises: 
Create Date: 2020-05-28 17:44:29.932001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d9b914caac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender_predict', sa.String(length=64), nullable=False),
    sa.Column('correct', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_name_correct'), 'name', ['correct'], unique=False)
    op.create_index(op.f('ix_name_gender_predict'), 'name', ['gender_predict'], unique=False)
    op.create_index(op.f('ix_name_name'), 'name', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_name_name'), table_name='name')
    op.drop_index(op.f('ix_name_gender_predict'), table_name='name')
    op.drop_index(op.f('ix_name_correct'), table_name='name')
    op.drop_table('name')
    # ### end Alembic commands ###
